### ISSUE TITLE
Native Test detection

### ISSUE THREAD

**Issue by nitanmarcel** [snake-4/Zygisk-Assistant#26] opened 2024-05-06 08:09 UTC
**Describe the bug**
An app called Native Detector, is able to detect a lot of changes to the system. The chances for the detection used there to be used in an actual app they are pretty small since it's closed sourced but maybe there's a way to hide them?

**Steps To Reproduce**

1. Install https://t.me/nullptr_dev/98
2. Open it
3. Notice the detection spam

**Context**

 - Device: OnePlus6T 
 - OS: Android 14 - custom ROM
 - Version APatch: 0.10.5
 - Other Root Module(s): QuickSwitch, systemless hosts, ZygiskNext, LSPosed, Zygisk Assistant 
 - LSPosed Module(s): None in the system framework, just 1 to bypass SSL pinning in targeted apps

**Logcat**

![Screenshot_20240506-105708_Native Test](https://github.com/snake-4/Zygisk-Assistant/assets/41646249/58f1c0c9-c32a-472e-9870-5f81f15a7a02)

**Comment by snake-4** [comment] 2024-05-06 13:17
Please use the latest debug build and attach logs. Also, if you're injecting an Xposed module to Native Test, don't.

**Comment by snake-4** [comment] 2024-05-06 14:44
I'll be closing this issue. Most of those detections are caused by LSPosed and "Permission Loophole" is a problem with KSU. The remaining ones were already fixed in the latest build.

**Closed by snake-4** 2024-05-06 14:44 UTC
Labels: bug

**Comment by nitanmarcel** [comment] 2024-05-06 14:51
> I'll be closing this issue. Most of those detections are caused by LSPosed and "Permission Loophole" is a problem with KSU. The remaining ones were already fixed in the latest build.

Yeah, disabling LSPosed got rid of some. Also I was using the artefact version when posting the issue.

![Screenshot_20240506-175004_APatch](https://github.com/snake-4/Zygisk-Assistant/assets/41646249/094db34b-56a0-4cb4-996e-562c5bebb1d0)
![Screenshot_20240506-175007_APatch](https://github.com/snake-4/Zygisk-Assistant/assets/41646249/4b0ad31f-3edf-4478-a183-73edbd6895e6)
![Screenshot_20240506-174951_Native Test](https://github.com/snake-4/Zygisk-Assistant/assets/41646249/4cadfb5c-9968-4995-9973-b890e6857794)

**Comment by snake-4** [comment] 2024-05-06 14:58
Refer to #24 for the ZygistNext detection. Also if you try again with LSPosed enabled but logging disabled in LSPosed settings, the property detection shouldn't happen.
